### ISSUE TITLE
Use flexbox?

### ISSUE THREAD

**Issue by alecive** [alecive/alecive.github.io#6]
This might be an option, but I don't know if it is worth it or not for my purposes. Cc @cciliber

**Comment by cciliber** [comment]
It is worth doing it if you never used flexbox for a real project, since "you only learn something when you use it in practice".

And it's fun!

**Comment by alecive** [comment]
The problem is the time I would need to do it :smile: 
Right now I'm using twitter bootstrap's grid system, and i would be really painful to change everything. But I will do it! At some point :)

**Comment by alecive** [comment]
Ok I've decided. It's not worth it :)
Bootstrap handles everything for you, and it provides a great platform that by the way allows for flexbox layouts, so I will not for the time being use them (but I'm open to in the future).
